# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.


services:
  server:
    build:
      context: .
    ports:
      - 9090:8082  #host out: config in (application.yml)
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
      - DB_HOST
      - DB_PORT
    develop:
      watch:
        - action: rebuild
          path: .

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:

# secrets:
#   db-password:
#     file: db/password.txt
# RVD tech solutions, Oshodi Axis +2349125064945
#Remote software engineer careers@planetscale.com